name: CI

on:
  push:
    branches:
      - main  # 当main分支有推送时触发CI

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的Ubuntu系统作为运行环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 检出代码到运行环境

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # 设置Python版本

      - name: Install dependencies
        run: pip install -r requirements.txt  # 安装项目依赖

      - name: Run tests
        run: pytest  # 运行测试用例